### ISSUE TITLE
disable automatic frame numbering

### ISSUE THREAD

**Issue by arlo-ml** [spacepxl/ComfyUI-HQ-Image-Save#15]
hi, thank you for your invaluable EXR nodes

Is there a way to write the file name exactly with the filename_prefix, without the frame numbering?
For example, rather than "filename.exr", It always writes "filename_0001_.exr"
But there might be some occasions we might not need to use the frame numbering

**Comment by spacepxl** [comment]
SaveEXRFrames will do what you're asking, if you use a file path without any %04d it will write to the exact unmodified path. Just know that in the case where there is no frame placeholder, and the batch size is > 1, it will only write the first image of the batch.

**Comment by arlo-ml** [comment]
ok, my fault
I used the Save EXR node. With this node, I could not find a way to avoid the versioning and frame numbering at the end of the filename
I tried with the Save EXR Frames, and it works exactly as you said
