### ISSUE TITLE
Error in saving EXR

### ISSUE THREAD

**Issue by v4r4rth** [spacepxl/ComfyUI-HQ-Image-Save#2]
Getting this in the terminal -

```
got prompt
saving images:   0%|                                                                                                                                                                                      | 0/1 [00:00<?, ?it/s][
 WARN:0@1304.865] global grfmt_exr.cpp:102 cv::initOpenEXR imgcodecs: OpenEXR codec is disabled. You can enable it via 'OPENCV_IO_ENABLE_OPENEXR' option. Refer for details and cautions here: https://github.com/opencv/opencv/issues/21326
saving images: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.95it/s]
Prompt executed in 3.59 seconds
```
TIFF saving is working but EXR is not.. please suggest how I can fix this!

**Comment by v4r4rth** [comment]
Fixed! I am on windows so I was getting the export command to set the environment variable wrong, after a set OPENCV_IO_ENABLE_OPENEXR=1 it got working!

**Comment by spacepxl** [comment]
That's an odd one, it's supposed to get set automatically by [nodes.py](https://github.com/spacepxl/ComfyUI-HQ-Image-Save/blob/3c79bdbb627580086005d680bf5f20c4fdc63d31/nodes.py#L6)

I added back the information on how to fix it to the readme in case anyone else has the same issue.
