### ISSUE TITLE
Error when loading EXRs from Octane

### ISSUE THREAD

**Issue by rethink-studios** [spacepxl/ComfyUI-HQ-Image-Save#7]
Hey hey!!
I rendered frames from Octane, and we're receiving this error below:
The files rendered at 16bit..
Any ideas?

!!! Exception during processing!!! too many indices for array: array is 2-dimensional, but 3 were indexed
Traceback (most recent call last):
  File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-HQ-Image-Save\nodes.py", line 158, in load
    rgbFrame, maskFrame = load_EXR(framepath, linear_to_sRGB)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-HQ-Image-Save\nodes.py", line 29, in load_EXR
    rgb = np.flip(image[:,:,:3], 2).copy()
                  ~~~~~^^^^^^^^
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

**Comment by spacepxl** [comment]
Double check that your EXR is actually RGB or RGBA. That error message seems to imply that it's only loading a single channel, which could mean that the render data is actually in a different layer other than RGBA, which is not supported by OpenCV.

**Comment by spacepxl** [comment]
Should be fixed now with https://github.com/spacepxl/ComfyUI-HQ-Image-Save/commit/71e242c746e9170e53e00919b12625317a7571e5
