### ISSUE TITLE
does not save

### ISSUE THREAD

**Issue by Hellrunner2k** [spacepxl/ComfyUI-HQ-Image-Save#8]
WARN:0@148.342] global grfmt_exr.cpp:102 cv::initOpenEXR imgcodecs: OpenEXR codec is disabled. You can enable it via 'OPENCV_IO_ENABLE_OPENEXR' option. Refer for details and cautions here: https://github.com/opencv/opencv/issues/21326

![image](https://github.com/user-attachments/assets/42ac6226-cf58-423d-bc60-a3c253ac82a8)

**Comment by spacepxl** [comment]
That os.environ line should work, it does for me, but if not you can set the environment variable before launching comfy instead by adding it to your launch script. Windows example for run_nvidia_gpu.bat:

```
set OPENCV_IO_ENABLE_OPENEXR=1
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --fp32-vae

pause
```
(If you're on linux I trust you can figure out the equivalent)

**Comment by ludnny** [comment]
I managed to make it work doing this (on Windows):

Right-click on "This PC" or "Computer" on your desktop or in File Explorer.
Click on "Properties."
Click on "Advanced system settings."
In the System Properties window, click on the "Environment Variables" button.
In the Environment Variables window, under "System variables," click "New."
Set the "Variable name" to **OPENCV_IO_ENABLE_OPENEXR** and the "Variable value" to **1**.
Click "OK" to close all dialog boxes.

Then restart everything.
