### ISSUE TITLE
does not support pixel values ​​below 0 and above 1, clamped image

### ISSUE THREAD

**Issue by vinavfx** [spacepxl/ComfyUI-HQ-Image-Save#9]
does not support pixel values ​​below 0 and above 1, clamped image

**Comment by spacepxl** [comment]
If you use sRGB, yes it's clamped. If you disable sRGB, you can use raw/linear unclamped images, although most nodes won't expect that and either clamp and/or break. The non-sRGB option is actually intended to be used with EXRs that have a reversible LUT (including display transform) baked in. This allows round-trip between nuke or other applications and comfy, while preserving 32bit depth and letting ML models operate in the color ranges they expect.

Edit: in [spacepxl/ComfyUI-Image-Filters](https://github.com/spacepxl/ComfyUI-Image-Filters) I have a few nodes that can handle linear images (Exposure Adjust, Tonemap, UnTonemap)

**Comment by vinavfx** [comment]
You are absolutely right, thanks, it is a problem with my repository.
